services:
  tg_bot:
    build:
      context: ./services/tg_bot
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./services/tg_bot/.env
    volumes:
      - ./services/tg_bot/src:/app/src

  backend:
    build:
      context: ./services/backend
      dockerfile: Dockerfile
    restart: always
